### ISSUE TITLE
Labels on resources

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/sapi#4]
In the DsAPI documentation, it states that resource descriptions in JSON will be returned optionally with an `@label` property if the actual resource has an `rdfs:label`. DsAPI does not currently conform to that requirement, and Chris' opinion is that doing so would be complicated in the current stream processing architecture.

I think we do need to address this in the new API design.

Further complications to consider: multiple label properties (`rdfs:label` vs. `skos:prefLabel`), interaction with language filtering

**Comment by der** [comment]
The new sapi is a replacement for the old sapi and not dsapi, don't think requirement makes sense for sapi.

**Comment by ijdickinson** [comment]
OK, I guess I don't understand the objectives then.
